### ISSUE TITLE
Watching doesn't work when calling `mix.browserify()` multiple times 

### ISSUE THREAD

**Issue by jacobmllr95** [JeffreyWay/laravel-elixir-browserify#2]
I have a setup where I generate a different bundled JavaScript file for each of my sites because the content of the sites differs a lot. To generate these bundled scripts I call `mix.browserify()` for each script (about 20 times).

When calling `gulp watch` nothing happens and making changes doesn't make any difference.
When I'am bundling only one script everything works as expected.

**Comment by adamszigeti** [comment]
I don't have time to cerate a pull request, but this one worked for me: changing the "isWatching" method call to a property call (so basically just removing the brackets from the end of the line) just solved all my problems.

The culprit can be found at "./node_modules/laravel-elixir-browserify-official/browserify.js", on line 162. :)

Edit: My actual problem was whenever I ran "gulp" in the command line, gulp just crashed. This fixed it, and I think it will solve your problem too, since this is connected to the watching.
